// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnKhDe8APqJcQU_jmKDcYPg1761MPe9Q4',
    appId: '1:357652145252:web:dd88c7ff755bad96ffeb71',
    messagingSenderId: '357652145252',
    projectId: 'mynote-app-4ffd6',
    authDomain: 'mynote-app-4ffd6.firebaseapp.com',
    storageBucket: 'mynote-app-4ffd6.firebasestorage.app',
    measurementId: 'G-6D0WZ71HNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANQjuhhUH-sllKtIKaINzyEqavMPlqkl8',
    appId: '1:357652145252:android:93b1d4ed812d69a7ffeb71',
    messagingSenderId: '357652145252',
    projectId: 'mynote-app-4ffd6',
    storageBucket: 'mynote-app-4ffd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOiOxkyq1MXrF9bkuOT1qvgl5JqjpQ0N0',
    appId: '1:357652145252:ios:4505e8aa9085780cffeb71',
    messagingSenderId: '357652145252',
    projectId: 'mynote-app-4ffd6',
    storageBucket: 'mynote-app-4ffd6.firebasestorage.app',
    iosBundleId: 'com.example.mynoteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOiOxkyq1MXrF9bkuOT1qvgl5JqjpQ0N0',
    appId: '1:357652145252:ios:4505e8aa9085780cffeb71',
    messagingSenderId: '357652145252',
    projectId: 'mynote-app-4ffd6',
    storageBucket: 'mynote-app-4ffd6.firebasestorage.app',
    iosBundleId: 'com.example.mynoteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnKhDe8APqJcQU_jmKDcYPg1761MPe9Q4',
    appId: '1:357652145252:web:c98dda0b9de4a27dffeb71',
    messagingSenderId: '357652145252',
    projectId: 'mynote-app-4ffd6',
    authDomain: 'mynote-app-4ffd6.firebaseapp.com',
    storageBucket: 'mynote-app-4ffd6.firebasestorage.app',
    measurementId: 'G-9N8G66XL36',
  );
}
